# Generated by Django 4.1 on 2022-08-08 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Наименование')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)], verbose_name='Код УЕ')),
                ('type', models.CharField(choices=[('МФУ', 'МФУ'), ('Принтер лазерный', 'Принтер лазерный'), ('Принтер струйный', 'Принтер струйный')], max_length=50, verbose_name='Тип устройства')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('slug', models.SlugField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Склад')),
            ],
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('query', models.CharField(max_length=50, verbose_name='Заявка')),
                ('cartridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ink.cartridge', verbose_name='Картридж')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ink.device', verbose_name='Устройство')),
            ],
        ),
        migrations.AddField(
            model_name='cartridge',
            name='storage',
            field=models.ManyToManyField(to='ink.storage'),
        ),
    ]
