# Generated by Django 4.1 on 2022-08-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name': 'картридж', 'verbose_name_plural': 'Картриджи'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='mount',
            options={'verbose_name': 'установку картриджа', 'verbose_name_plural': 'Установки картриджей'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='slug',
        ),
    ]
