# Generated by Django 4.1 on 2022-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0008_alter_cartridge_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mount',
            name='date',
        ),
        migrations.AddField(
            model_name='mount',
            name='date_mount',
            field=models.DateField(auto_now_add=True, verbose_name='Дата установки'),
            preserve_default=False,
        ),
    ]
