# Generated by Django 4.1 on 2022-08-11 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0011_alter_mount_date_mount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mount',
            name='date_mount',
        ),
        migrations.AddField(
            model_name='mount',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='query',
            field=models.CharField(max_length=50, verbose_name='Заявка'),
        ),
    ]
