# Generated by Django 4.1 on 2022-08-11 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0012_remove_mount_date_mount_mount_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата установки'),
        ),
    ]
