# Generated by Django 4.1 on 2022-08-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0015_employe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
    ]
