# Generated by Django 4.1 on 2022-09-11 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0016_rename_employe_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Остаток не может быть меньше нуля.')], verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='device',
            name='unit_id',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Минимум 1 символ'), django.core.validators.MaxLengthValidator(limit_value=4, message='Максимум 4 символа')], verbose_name='Код УЕ'),
        ),
    ]
