# Generated by Django 4.1 on 2022-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0020_device_device_url_alter_device_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_url',
            field=models.URLField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
    ]
