# Generated by Django 4.1 on 2022-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0022_rename_date_mount_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_url',
            new_name='ip',
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
    ]
