# Generated by Django 4.1 on 2022-09-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0028_remove_device_cartridge_device_cartridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='cartridge',
        ),
        migrations.AddField(
            model_name='device',
            name='cartridge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ink.cartridge', verbose_name='Картридж'),
        ),
    ]
