# Generated by Django 4.1 on 2022-09-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0030_remove_device_cartridge_device_cartridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cartridge',
            field=models.ManyToManyField(to='ink.cartridge', verbose_name='Картридж'),
        ),
    ]
