# Generated by Django 4.1 on 2022-09-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0031_alter_device_cartridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='cartridge',
        ),
        migrations.RemoveField(
            model_name='device',
            name='image',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='device',
            name='serial_number',
        ),
    ]
