# Generated by Django 4.1 on 2022-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0034_alter_device_unit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cartridge',
            field=models.ManyToManyField(to='ink.cartridge', verbose_name='Картридж'),
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, default='default_device.png', null=True, upload_to='img/devices', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.URLField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
    ]
