# Generated by Django 4.1 on 2022-09-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0043_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/devices', verbose_name='Изображение'),
        ),
    ]
