# Generated by Django 4.1 on 2022-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0046_remove_cartridge_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='storage',
            field=models.ManyToManyField(to='ink.storage'),
        ),
    ]
