# Generated by Django 4.1 on 2022-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0050_alter_cartridge_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mount',
            name='counter',
            field=models.PositiveIntegerField(null=True, verbose_name='Счётчик'),
        ),
        migrations.AddField(
            model_name='mount',
            name='initiator',
            field=models.CharField(max_length=100, null=True, verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='mount',
            name='note',
            field=models.CharField(max_length=200, null=True, verbose_name='Примечание'),
        ),
    ]
