# Generated by Django 4.1 on 2022-09-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0052_alter_mount_counter_alter_mount_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='initiator',
            field=models.CharField(max_length=100, null=True, verbose_name='Инициатор'),
        ),
    ]
