# Generated by Django 4.1 on 2022-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0053_alter_mount_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='color',
            field=models.BooleanField(default=False, verbose_name='Цветной'),
        ),
        migrations.AddField(
            model_name='device',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
