# Generated by Django 4.1 on 2022-09-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0054_device_color_device_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='color',
            field=models.CharField(choices=[('C', 'Cyan'), ('M', 'Magenta'), ('Y', 'Yellow'), ('K', 'Black')], default='K', max_length=1, verbose_name='Цвет'),
        ),
    ]
