# Generated by Django 4.1 on 2022-10-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0055_cartridge_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
