# Generated by Django 4.1 on 2022-10-05 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ink', '0056_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mount',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartridgePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('invoice_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Накладная')),
                ('qty_ordered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('cartridge_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cartridgepurchase', to='ink.cartridge')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
