# Generated by Django 4.1 on 2022-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0057_mount_creator_cartridgepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cartridge',
            field=models.ManyToManyField(to='ink.cartridge', verbose_name='Совместимые картриджи'),
        ),
    ]
