# Generated by Django 4.1 on 2022-10-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0058_alter_device_cartridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='storage',
        ),
        migrations.AddField(
            model_name='storage',
            name='cartridge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ink.cartridge', verbose_name='Картридж'),
        ),
        migrations.AddField(
            model_name='storage',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
