# Generated by Django 4.1 on 2022-10-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0059_remove_cartridge_amount_remove_cartridge_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ink.cartridgepurchase', verbose_name='Поступление'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='cartridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ink.cartridge', verbose_name='Картридж'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(choices=[('A', 'Архангельск'), ('H', 'Нарьян-Мар')], max_length=15, verbose_name='Склад'),
        ),
    ]
