# Generated by Django 4.1 on 2022-11-02 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0061_cartridge_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='cartridge',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='count',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='purchase',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Остаток не может быть меньше нуля')], verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='storage',
            field=models.ManyToManyField(default='Архангельск', to='ink.storage', verbose_name='Склад'),
        ),
    ]
