# Generated by Django 4.1 on 2022-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0062_remove_cartridge_qty_remove_storage_cartridge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='storage',
            field=models.ManyToManyField(default='A', to='ink.storage', verbose_name='Склад'),
        ),
    ]
