# Generated by Django 4.1 on 2022-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0063_alter_cartridge_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='storage',
            field=models.ManyToManyField(default='Архангельск', to='ink.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(choices=[('Архангельск', 'Архангельск'), ('Нарьян-Мар', 'Нарьян-Мар')], max_length=15, verbose_name='Склад'),
        ),
    ]
