# Generated by Django 4.1 on 2022-11-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0064_alter_cartridge_storage_alter_storage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mount',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ink.storage', verbose_name='Склад'),
        ),
    ]
